function CA_ROI = createCA_ROI(ROI, Params, tempROI)

    CA_ROI = tempROI;
    CA_ROI.roi = [Params.xLow,Params.yLow,Params.roiWidth,Params.roiHeight];
    CA_ROI.enclosing_rect = [Params.xLow, Params.yLow,...
        Params.xHigh,Params.yHigh];
    CA_ROI.ym = Params.xLow+Params.roiWidth/2;
    CA_ROI.xm = Params.yLow+Params.roiHeight/2;
    CA_ROI.boundary = ...
        {[Params.yLow,Params.xLow;...
        Params.yLow,Params.xHigh;...
        Params.yHigh,Params.xHigh;...
        Params.yHigh,Params.xLow;...
        Params.yLow,Params.xLow]};

end
