function Params = defineROIs()
    roiInput = inputdlg(...
        {'Enter ROI width:', 'Enter ROI height:'}, ...
        'Tiled Image Parameters', ...
        [1 50; 1 50],...
        {'512', '512'});

    Params.roiWidth = floor(str2double(roiInput(1)));
    Params.roiHeight = floor(str2double(roiInput(2)));
    
    thresholdInput = inputdlg(...
        {'Enter threshold for number of pixels (%):', 'Enter threshold for pixel intensity (%):'}, ...
        'Tiled Image Parameters', ...
        [1 50; 1 50],...
        {'5', '1'});
    
    Params.pixelNumThresh = floor(str2double(thresholdInput(1)));
    Params.pixelIntensityThresh = floor(str2double(thresholdInput(2)));
    
return