function Params = defineROIs()
    

    userInput = inputdlg(...
        {'Enter ROI width:', 'Enter ROI height:'}, ...
        'Tiled Image Parameters', ...
        [1 50; 1 50],...
        {'512', '512'});

    Params.roiWidth = floor(str2double(userInput(1)));
    Params.roiHeight = floor(str2double(userInput(2)));

return